version: '3.7'

services:
  hoteldb:
    image: postgres:14.4
    container_name: alten-hotel-pg
    hostname: alten-hotel-pg
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $HOTEL_DB_USER
      POSTGRES_PASSWORD: $HOTEL_DB_PSWD
      POSTGRES_DB: $HOTEL_DB
    volumes:
      - ./scripts/create-altenhotel-db.sh:/docker-entrypoint-initdb.d/create-altenhotel-db.sh
    networks:
      - alten-hotel-network

networks:
  alten-hotel-network:
    driver: bridge
    name: alten-hotel-network
